# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
seed: 0
device: 'mps'
rounds: 5
epochs: 15
patience: 3

# Model
logger: 'Run'
dataset: 'rt'
model: 'DNN'
density: 0.80

# Debug configuration
debug: 0
saved: 1
record: 0
verbose: 1
experiment: 0
path: './datasets/'

# Learning configuration
bs: 32
lr: 0.000001
decay: 0.000001

# Training tools
loss_func: 'CrossEntropyLoss'
optim: 'Adam'
program_test: 0

# Hyperparameter
order: 3
retrieve_method: 'L2'
dimension: 32

# Other configuration
ablation: 0
classification: 1

---
# Config description for each option
experiment: 'Run the experiment now!'
